### ISSUE TITLE
min and max are automatically included in steps range

### ISSUE THREAD

**Issue by sbtly** [TanStack/ranger#20]
It seems like min and max values are automatically included in custom steps range.

```
min: 0,
max: 10,
steps: [2, 5, 6]
```

In this situation, handle should only be in one of the steps. But instead, handle can also be in 0 and 10.

I can’t just change min/max value, because I need to align each step’s position to another line graph.

**Comment by rkulinski** [comment]
I'm not sure if it's still an issue.  Anyhow, with new version  you are not tied with UI so you can adjust elements visually however you want.
