### ISSUE TITLE
Support for react@17.0.1

### ISSUE THREAD

**Issue by deadcoder0904** [TanStack/ranger#22]
I get the following error when I try to `npm install react-ranger`:

> Could not resolve dependency:
npm ERR! peer react@"^16.6.3" from react-ranger@2.1.0

Can you update the `peerDependencies` section & release a new version?

https://github.com/tannerlinsley/react-ranger/blob/d912f893d2efb125d271162e36ee8531b5fd4f39/package.json#L35-L37

**Comment by sevast1an** [comment]
Yeah, I also have this issue (( installed id with force and it's not working as it should, on point drag it refreshes the page ((( please update for the new react version

**Comment by VulcanTech-io** [comment]
yarn (the package manager) just warns you and will still let you use it. I have no problems with the library using 17.0.2. But obviously this issue should be fixed.

**Comment by tannerlinsley** [comment]
I’m planning a Typescript rewrite for the entire library.

Tanner Linsley

**Comment by VulcanTech-io** [comment]
@tannerlinsley Need any help?

**Comment by tannerlinsley** [comment]
I mean, I can always use help! The roadmap is this:

- Clone the next branch from github.com/tannerlinsley/react-location as a starting point
- Replace all react-location stuff with react-ranger including home page, documentation, examples
- Migrate all of the existing react-ranger code from JS to TS
- 🚢

**Comment by ParrotStone** [comment]
Any updates on this issue?

**Comment by tannerlinsley** [comment]
Yep

Tanner Linsley
Sent with Spark

**Comment by andrejcesen** [comment]
You can [use overrides in `package.json` to force spec for a specific dependency](https://stackoverflow.com/a/74734729).

**Comment by jeadys** [comment]
It has been over 2 years, are there any updates? Trying to use this with react 18.2.0

**Comment by VulcanTech-io** [comment]
> It has been over 2 years, are there any updates? Trying to use this with react 18.2.0

I use it with react@latest with no problems

**Comment by rkulinski** [comment]
Also https://www.npmjs.com/package/@tanstack/react-ranger works.
