### ISSUE TITLE
When the value of the min is equal to a negative number. Then drag one of the handles to 0. the segments change color incorrectly

### ISSUE THREAD

**Issue by alongolan1991** [TanStack/ranger#32]
<h1>When the value of the min is equal to a negative number. Then drag one of the handles to 0. the segments change color incorrectly </h1>

<p> sendbox Code </p>
<a href="https://codesandbox.io/s/determined-meadow-xso5fr"> Codesendbox </a>
<br>
<br>
<br>

<img width="1455" alt="Screen Shot 2022-07-12 at 16 38 27" src="https://user-images.githubusercontent.com/33026025/178503496-5d398186-6fc8-49b3-aff9-bba731d6661e.png">

**Comment by rkulinski** [comment]
New version of the library doesn't have this issue.
https://tanstack.com/ranger/v1
Hence, closing this one.
